openapi: 3.0.3
info:
  version: 1.0.0
  title: Product API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://api.myproduct-service.io'
paths:
  '/products/{product_id}/clowncopterize':
    parameters:
      - $ref: '#/components/parameters/ProductID'
    post:
      summary: Clowncopterize product
      description: Clowncopterizes the given product.
      operationId: product-clowncopterize
      x-internal: true
      tags:
        - Products
      responses:
        '204':
          description: OK

components:
  parameters:
    ProductID:
      name: product_id
      in: path
      required: true
      description: The ID of the product.
      schema:
        type: string
        format: ulid
tags:
  - name: Products
